services:
  backend:
    build: ./backend
    container_name: devops-demo-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    container_name: devops-demo-frontend
    ports:
      - "3000:80"
    environment:
      # Frontend תמיד יפנה ל-backend הנכון
      - VITE_API_BASE=http://host.docker.internal:4000/api
    depends_on:
      - backend
